[env]
BINARY_FILE = "game"

[tasks.build]
description = "Builds the executable"
run = "odin build ."
alias = "b"

[tasks.test]
description = "Runs the tests."
run = "odin test tests"
alias = "t"

[tasks.format]
description = "Formats every file."
run = "odinfmt . -w"
alias = "f"

[tasks.check]
description = "Checks the source code for problems."
run = "odin check . -vet -strict-style -vet-packages:tests,animator"
alias = "c"

[tasks.run]
description = "Runs the game."
run = "odin run ."
alias = "r"

[tasks.debug]
description = "Runs the game in debug mode."
run = "odin run . -debug"
alias = "d"

[tasks.release]
description = "Builds an optimized release binary."
run = "odin build . -o:size -no-bounds-check -disable-assert && strip -x $BINARY_FILE"
alias = "rel"

[tasks.clean]
description = "Cleans up unnecessary files."
run = [
  "rm -f ./$BINARY_FILE",
  "rm -rf ./$BINARY_FILE.dSYM",
  "rm -rf ./tests.bin",
  "rm -rf ./tests.bin.dSYM",
]
