[env]
BINARY = "game"
DEBUG_BINARY = "game_debug"

[tasks.build]
description = "Builds the executable"
run = "odin build src -out:$BINARY"
alias = "b"

[tasks.test]
description = "Runs the tests."
run = "odin test tests"
alias = "t"

[tasks.format]
description = "Formats every file."
run = "odinfmt . -w"
alias = "f"

[tasks.check]
description = "Checks the source code for problems."
run = "odin check src -vet -strict-style -vet-packages:tests,animator"
alias = "c"

[tasks.run]
description = "Runs the game."
run = "odin run src"
alias = "r"

[tasks.debug]
description = "Runs the game in debug mode."
run = "odin run src -debug -out:$DEBUG_BINARY"
alias = "d"

[tasks.release]
description = "Builds an optimized release binary."
run = "odin build src -o:size -no-bounds-check -disable-assert -out:$BINARY && strip -x $BINARY"
alias = "rel"

[tasks.clean]
description = "Cleans up unnecessary files."
run = [
  "rm -f ./$BINARY ./$DEBUG_BINARY",
  "rm -rf ./$BINARY.dSYM ./$DEBUG_BINARY.dSYM",
  "rm -rf ./tests.bin ./src.bin",
  "rm -rf ./tests.bin.dSYM",
]
